spspring.application.name=payment-service
server.port=8089

# CONFIGURACIÓN H2 (Persistente en archivo)
spring.datasource.url=jdbc:h2:file:./data/PaymentDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# ESTRATEGIA DE BASE DE DATOS (Crucial para import.sql)
# Usamos 'create-drop' para que limpie y cargue los datos de prueba cada vez
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# CONSOLA H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# LOGS (Para ver qué hace Spring)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Cambia la D por DEBUG
logging.level.org.hibernate.sql=DEBUG