# Define el nombre interno de la aplicación.
# Puede aparecer en logs, monitoreo o microservicios.

spring.application.name=category-service

# IMPORTANTE:
# La base de datos se guardara en la ruta asignada.
spring.datasource.url=jdbc:h2:file:./data/testdb

#la carpeta con el archivo se creara cuando se necesite guardar informacion
#por primera vez.


# Driver JDBC que Spring usará para comunicarse con H2
# Spring normalmente lo detecta solo, pero se suele
# especificar explícitamente por claridad.
spring.datasource.driverClassName=org.h2.Driver


# Usuario de la base de datos
spring.datasource.username=sa

# Contraseña de la base de datos
spring.datasource.password=sa

# CONSOLA WEB DE H2
# ----------------------------------------------------

# Habilita la interfaz web de H2.
# Permite ver tablas, ejecutar SQL y revisar datos
# desde el navegador.
spring.h2.console.enabled=true


# Ruta para acceder a la consola H2.
# La URL final normalmente será:
# http://localhost:8080/h2-console
spring.h2.console.path=/h2-console


# CONFIGURACIÓN JPA / HIBERNATE
# ----------------------------------------------------

# Define el dialecto SQL que Hibernate utilizará.
# Hibernate adapta las consultas SQL según el motor
# de base de datos.
#
# En este caso:
# H2Dialect = sintaxis SQL para H2.
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# Controla qué hará Hibernate con las tablas.
#
# Opciones importantes:
#
# create
# - Borra y crea todas las tablas al iniciar.
#
# update
# - Actualiza tablas sin borrar datos.
#
# create-drop
# - Crea al iniciar y elimina al cerrar.
#
# validate
# - Solo valida que las tablas coincidan.
#
# none
# - No modifica nada.
#
# Para proyectos académicos normalmente:
# update o create.
spring.jpa.hibernate.ddl-auto=update


# Muestra las consultas SQL en consola.
# Muy útil para aprender y depurar.
spring.jpa.show-sql=true


# ----------------------------------------------------
# FORMATO DE SQL (OPCIONAL)
# ----------------------------------------------------

# Hace que el SQL mostrado en consola se vea ordenado
# y más legible.
spring.jpa.properties.hibernate.format_sql=true


# ----------------------------------------------------
# CONFIGURACIÓN OPCIONAL DE LOGS SQL
# ----------------------------------------------------

# Muestra las consultas SQL ejecutadas por Hibernate.
logging.level.org.hibernate.SQL=DEBUG


# Muestra parámetros enviados en consultas SQL.
# Útil para debugging avanzado.
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE