spring.application.name=category-service
server.port=8081


# IMPORTANTE:
# La base de datos se guardara en la ruta asignada.
spring.datasource.url=jdbc:h2:file:./data/CategoryDB
#la carpeta con el archivo se creara cuando se necesite guardar informacion
#por primera vez.


# Driver JDBC que Spring usará para comunicarse con H2
spring.datasource.driverClassName=org.h2.Driver


# USUARIO Y CONTRASEÑA DE LA BASE DE DATOS
spring.datasource.username=sa
spring.datasource.password=sa


# CONSOLA WEB DE H2:

# Habilita la interfaz web de H2.
# Permite ver tablas, ejecutar SQL y revisar datos
# desde el navegador.
spring.h2.console.enabled=true


# Ruta para acceder a la consola H2.
# La URL final normalmente será:
# http://localhost:8080/h2-console
spring.h2.console.path=/h2-console


# Define el dialecto SQL que Hibernate utilizará.
# Hibernate adapta las consultas SQL según el motor
# de base de datos.
# En este caso:
# H2Dialect = sintaxis SQL para H2.
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# update: para Actualizar tablas sin borrar datos.
spring.jpa.hibernate.ddl-auto=update


# Muestra las consultas SQL en consola.
# Muy útil para aprender y depurar.
spring.jpa.show-sql=true


# Hace que el SQL mostrado en consola se vea ordenado
# y más legible.
spring.jpa.properties.hibernate.format_sql=true


# CONFIGURACIÓN DE LOGS SQL:

# Muestra las consultas SQL ejecutadas por Hibernate.
logging.level.org.hibernate.SQL=DEBUG


# Muestra parámetros enviados en consultas SQL.
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE